odom2: "/icp_odom"

#The order of the values is x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az.
odom2_config: [true, true, true,
               true, true, true,
               true, true, true,
               true, true, true,
               true, true, true]

odom2_differential: true
odom2_relative: false

# ======== ADVANCED PARAMETERS ========
odom2_queue_size: 5