odom1: "/stereo_odom"

#The order of the values is x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az.
odom1_config: [true, true, true,
               true, true, true,
               true, true, true,
               true, true, true,
               true, true, true]

odom1_differential: false
odom1_relative: true

# ======== ADVANCED PARAMETERS ========
odom1_queue_size: 5